### ISSUE TITLE
Is the calcium concentration plot working for the OpenWorm muscle model?

### ISSUE THREAD

**Issue by slarson** [openworm/org.geppetto.samples#27]
When the OpenWorm muscle model sample runs, the value for calcium concentration is plotted, but remains flat no matter what happens to the membrane potential of the muscle or the neuron.  In the tree visualizer, the calcium concentration value appears to be changing, but this is not reflected in the plot.  Is the calcium concentration variable in the tree widget actually driving the plot?  How would a contributor be able to figure this out for themselves?

**Comment by tarelli** [comment]
@slarson Can you add a screnshot for this?

**Comment by tarelli** [comment]
I think this is what you refer to, as you can see it's e-9 in the tree widget, the scale for the plotting needs to be update in the script for the sample otherwise you can't discern such a small value.
![screen shot 2015-02-08 at 22 05 38](https://cloud.githubusercontent.com/assets/81127/6098694/b4ea7e5e-afde-11e4-9550-cb1b4fd56239.png)

See this line to be updated
https://github.com/openworm/org.geppetto.samples/blob/development/LEMS/MuscleModel/script.js#L14
I won't do it myself to give a chance to people to play with this.

**Comment by slarson** [comment]
Yes that's it!  I will spin out an issue to address this.  It does look like an existing issue openworm/org.geppetto.frontend#87 would also help here
